### ISSUE TITLE
Directory如何显示？

### ISSUE THREAD

**Issue by amywushu** [itisbenjamin/Nice_Blog#4]
你好，请问一下这个模板的博文中Directory应该如何显示呢？是有什么设置吗？我的md文件格式跟您例子里面的一样，但是就是没有目录。谢谢您~麻烦啦

**Comment by itisbenjamin** [comment]
Please read the whole project, especially the JS file. 
Nice_Blog/js/main.js

**Comment by amywushu** [comment]
谢谢您的回答  是这样的，我同样的文件用 jekyll 搭起来的服务预览是有 Directory 的  但是传到 github 上目录部分就只显示了一个 Directory 。标题目录显示不出来，请问您知道是什么原因吗？谢谢您

**Comment by itisbenjamin** [comment]
@amywushu

If you are sure that there is nothing wrong, please delete the whole repo and upload it again. Sometimes there are wired bugs show up in Jekyll since technology will never be completely developed. 
When I was working on another project, the only bug is caused by a simple blank line. 

Well, if this does not work again, please send me an email through gabrielchen001@gmail.com because I am too busy to check this GitHub account everyday.
